[versions]
kotlin = "2.4.10"
sysinfo-kmp = "1.0.1"
sdl-kmp = "1.0.10"
imgui-kmp = "1.0.5"
agp = "9.3.2"

[libraries]
sysinfo-kmp = { module = "cn.enaium:sysinfo-kmp", version.ref = "sysinfo-kmp" }
sdl-kmp = { module = "cn.enaium.sdl:sdl-kmp", version.ref = "sdl-kmp" }
imgui-kmp = { module = "cn.enaium.imgui:imgui-kmp", version.ref = "imgui-kmp" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
